# Generated by Django 6.0.4 on 2026-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
